[workspace]
members = [ 'crates/cli' , "crates/core", "crates/daemon", "crates/storage"]
resolver = "3"

[workspace.dependencies]
core = { path = "./crates/core" }
storage = { path = "./crates/storage" }
