[workspace]
members = [ 'crates/cli' , "crates/core", "crates/daemon", "crates/storage"]
resolver = "3"

[workspace.dependencies]
vlt_crypto = { path = "./crates/core" }
vlt_store = { path = "./crates/storage" }
